### ISSUE TITLE
Write the project documentation

### ISSUE THREAD

**Issue by ioan-h** [crowdy-ca/angular2-semantic#9]
- [x] Write the read-me file
  - [x] A quick summary of the project
  - [x] An installation guide
  - [x] How to compile from source
  - [x] A list of the supported features (will reference the wiki)
  - [x] A roadmap (will reference the wiki)
- [x] Write the contribution guidelines
  - [x] How to write an issue
  - [x] How to write a commit message
  - [x] A DoD
  - [x] Mention the up-for-grabs tag
- [x] Write the wiki for the general aspects of the project
  - [x] The currently supported feature list
  - [x] A release notes section
  - [x] The project's roadmap
  - [x] A section for writing the specifications of the features

**Comment by kawazoe** [comment]
The read-me should be more about how to use the project than how to contribute to it. Based on this. I think it should contain:
1. A quick summary of the project
2. An installation guide
3. How to compile from source
4. A list of the supported features (will reference the wiki)
5. A roadmap (will reference the wiki)

The contribution guidelines should include
1. How to write an issue
2. How to write a commit message
3. A DoD

**Comment by ioan-h** [comment]
The wiki should contain at least the following:

- [ ] The currently supported feature list
- [ ] A release notes section
- [ ] The project's roadmap
- [ ] A section for writing the specifications of the features

**Comment by ioan-h** [comment]
@kawazoe The subtask of writing the "compile from sources" readme section is dependent on issue #2

**Comment by ioan-h** [comment]
Readme is being drafted in the 9-documentation-readme branch
